name: Tests

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_DATABASE: posts-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v4
      - name: Copy .env
        run: |
          cd api
          cp .env.ci .env
      - name: Install Dependencies
        run: |
          cd api
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: |
          cd api
          php artisan key:generate
      - name: Directory Permissions
        run: |
          cd api
          chmod -R 777 storage bootstrap/cache
      - name: Run tests
        run: |
          cd api
          php artisan test
